### ISSUE TITLE
报错，POST()上报失败：Invalid URL

### ISSUE THREAD

**Issue by xi-yue-233** [Hoshinonyaruko/Yunzai-ws#1]
![image](https://user-images.githubusercontent.com/58218656/214222811-39c39a34-f9a8-4ab3-9746-79a58f120f12.png)
![image](https://user-images.githubusercontent.com/58218656/214222835-9b5d4267-7974-471e-860f-9587977124a7.png)
nb2报错
01-24 14:03:51 [INFO] uvicorn | ('127.0.0.1', 56504) - "WebSocket /" 403
01-24 14:03:51 [INFO] websockets | connection failed (403 Forbidden)
01-24 14:03:51 [INFO] websockets | connection closed

**Comment by TechOtakupoi233** [comment]
在端口号后面再加上 /onebot/v11/ws，即可识别
`ws://127.0.0.1:20038/onebot/v11/ws`

**Comment by xi-yue-233** [comment]
可以收到消息了，但是nb2那边报错：
`01-29 23:24:41 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.GenshinUID.GenshinUID.genshinuid_enka) failed.
Traceback (most recent call last):
  File "E:\qqbot-nonebot\Nonebot\nb2\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "E:\qqbot-nonebot\Nonebot\nb2\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 280, in send_card_info
    await matcher.finish(MessageSegment.image(im))
  File "D:\python-software\lib\site-packages\nonebot\internal\matcher\matcher.py", line 476, in finish
    await cls.send(message, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\internal\matcher\matcher.py", line 461, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 219, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "D:\python-software\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "D:\python-software\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\python-software\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "D:\python-software\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed`

**Comment by xi-yue-233** [comment]
![image](https://user-images.githubusercontent.com/58218656/215336454-9f717fad-199b-4b7b-888f-d9de5d2305e7.png)

**Comment by xi-yue-233** [comment]
![image](https://user-images.githubusercontent.com/58218656/215336526-581a05be-c427-47b1-9030-f02634988315.png)
现在的yaml配置

**Comment by TechOtakupoi233** [comment]
你是用的nonebot2装enka插件？这么搞的话我觉得还不如直接用Yunzai原生的miao-plugin。毕竟你要是就为了原神相关功能，Yunzai生态的插件功能已经挺完善了。
post_url是可以不填的，整行注释掉都可以，log就不会报错了。
我昨天折腾的是对接nonebot-plugin-pixivbot，问题就是收发文本没问题，但是到了发图那一步就会报错（报错实在太长），图发不出去。前端换到go-cqhttp就能正常发图了，也不影响原本Yunzai的运作...就是tx风控很恶心人。

**Comment by xi-yue-233** [comment]
> 

不，不是enka的问题，测试其他插件也是报这个错，posturl去掉也报这个错，其他插件测试了nonebot-plugin-epicfree，也是报这个actionfailed，用gocq就可以正常用

**Comment by TechOtakupoi233** [comment]
我也是ActionFailed，总之就是图发不出，文本正常。
nb2这边报错的时候Yunzai的log里会有一大串字符，不知道是不是Yunzai没有识别到要发的是图片就发不出去？

**Comment by xi-yue-233** [comment]
> 我也是ActionFailed，总之就是图发不出，文本正常。 nb2这边报错的时候Yunzai的log里会有一大串字符，不知道是不是Yunzai没有识别到要发的是图片就发不出去？

情况相同，好像只有文字能发出来，其他消息都发不了
